export const lightGrey = '#e6e3e1'
export const darkGrey = '#6f6a68'
export const lightBorder = '#BABABA'
export const darkBorder = '#8f8a88'
export const activeLight = '#f9eec7'
export const activeDark = '#906f68'

export const knobLight = '#d6d3d1'
export const knobDark = '#6f6a68'
export const knobMidiLight = '#a5d8ff'
export const knobMidiDark = '#1971c2'
export const knobMidiMultipleLight = '#f3bdb4'
export const knobMidiMultipleDark = '#c07367'

export const knobMidiUnmappedLight = '#d0ebff'
export const knobMidiUnmappedDark = '#7e8ca7'

export const lineColorLight = '#000000'
export const lineColorDark = '#C9C9C9'
export const strokeColorLight = '#FFFFFF'
export const strokeColorDark = '#000000'
export const attackPointColorLight = '#48a5f4'
export const attackPointColorDark = '#48a5f4'
export const decayPointColorLight = '#25c370'
export const decayPointColorDark = '#25c370'
export const sustainPointColorLight = '#ffa381'
export const sustainPointColorDark = '#ffa381'
export const releasePointColorLight = '#edd314'
export const releasePointColorDark = '#edd314'
export const keyOffPointColor = '#888888'
